---
- name: Copy Filebeat configuration.
  template:
    src: "{{ filebeat_template }}"
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat

- name: Ensure Filebeat SSL key pair directory exists.
  file:
    path: "{{ filebeat_ssl_dir }}"
    state: directory
    mode: 0755
  when: filebeat_ssl_key_file | default(false)

- name: Copy SSL key and cert for filebeat.
  copy:
    src: "{{ item }}"
    dest: "{{ filebeat_ssl_dir }}/{{ item | basename }}"
    mode: 0644
  with_items:
    - "{{ filebeat_ssl_key_file }}"
    - "{{ filebeat_ssl_certificate_file }}"
  notify: restart filebeat
  when:
    - filebeat_ssl_key_file | default(false)
    - filebeat_ssl_certificate_file | default(false)
